# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      # Check out the repo first
      - name: Checkout code
        uses: actions/checkout@v2
      # Run this action to publish gitbook
      - name: Publish
        uses: tuliren/publish-gitbook@v1.0.0
        with:
          # specify either github_token or personal_token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.PERSONAL_TOKEN }}

#   build:
#     name: build website
#     container: node:10
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Setup Node
#       uses: actions/setup-node@v1
#       with:
#         node-version: '10'

#     - name: Install Gitbook CLI
#       run: npm install -g gitbook-cli

#     - name: Build Gitbook
#       run: |
#         gitbook ls-remote
#         gitbook fetch 3.2.3
#         gitbook build . public

#     - name: Upload build files
#       uses: actions/upload-artifact@v2
#       with:
#         path: public

#     - name: Cache node modules
#       uses: actions/cache@v2
#       with:
#         path: node_modules/
